// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sb_ceak.Repositorio.Contexto;

namespace sb_ceak.Repositorio.Migrations
{
    [DbContext(typeof(SB_CEAKContexto))]
    [Migration("20230110214156_CargaTodasTabelas")]
    partial class CargaTodasTabelas
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Autores", b =>
                {
                    b.Property<int>("autor_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Nome_Autor")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.Property<int>("tipo_autor_id")
                        .HasColumnType("integer");

                    b.HasKey("autor_id");

                    b.ToTable("Autor");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.EmprestimoDevolucoes", b =>
                {
                    b.Property<int>("emp_dev_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dt_Data_Devolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Emprestimo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Prevista_Devolucao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("obra_id")
                        .HasColumnType("integer");

                    b.Property<int>("pessoa_id")
                        .HasColumnType("integer");

                    b.Property<int>("tipo_obra_id")
                        .HasColumnType("integer");

                    b.HasKey("emp_dev_id");

                    b.ToTable("EmprestimoDevolucao");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Funcoes", b =>
                {
                    b.Property<int>("funcao_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Nome_Funcao")
                        .IsRequired()
                        .HasColumnType("character(100)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.Property<int>("perfil_id");

                    b.HasKey("funcao_id");

                    b.HasIndex("perfil_id");

                    b.ToTable("Funcao");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Logs", b =>
                {
                    b.Property<int>("log_id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ds_Log_Realizado")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<DateTime>("dt_Data_Log")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("pessoa_id")
                        .HasColumnType("integer");

                    b.HasKey("log_id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Obras", b =>
                {
                    b.Property<int>("obra_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("autor_id")
                        .HasColumnType("integer");

                    b.Property<int>("autor_ps1_id")
                        .HasColumnType("integer");

                    b.Property<int>("autor_ps2_id")
                        .HasColumnType("integer");

                    b.Property<int>("autor_sec_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Ano_Publicacao_Obra")
                        .HasColumnType("character(30)");

                    b.Property<string>("ds_CDD_Obra")
                        .HasColumnType("character(30)");

                    b.Property<string>("ds_CDU_Obra")
                        .HasColumnType("character(30)");

                    b.Property<string>("ds_Codigo_Obra")
                        .IsRequired()
                        .HasColumnType("character(30)");

                    b.Property<string>("ds_Divulgadora_Obra")
                        .HasColumnType("character(30)");

                    b.Property<string>("ds_Duracao_Obra");

                    b.Property<string>("ds_Edicao_Obra")
                        .HasColumnType("character(30)");

                    b.Property<string>("ds_Editora_Obra")
                        .HasColumnType("character(50)");

                    b.Property<string>("ds_Mes_Ano_Publicacao_Obra")
                        .HasColumnType("character(30)");

                    b.Property<string>("ds_Nome_Obra")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Cadastro_Obra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.Property<int>("qtd_Pagina_Obra")
                        .HasColumnType("integer");

                    b.Property<int>("tipo_acervo_id")
                        .HasColumnType("integer");

                    b.Property<int>("tipo_obra_id")
                        .HasColumnType("integer");

                    b.HasKey("obra_id");

                    b.ToTable("Obra");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Operacoes", b =>
                {
                    b.Property<int>("operacao_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Nome_Operacao")
                        .IsRequired()
                        .HasColumnType("character(100)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("funcao_id");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.HasKey("operacao_id");

                    b.HasIndex("funcao_id");

                    b.ToTable("Operacao");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Parametros", b =>
                {
                    b.Property<int>("parametro_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_CEP_Parametro")
                        .IsRequired()
                        .HasColumnType("character(10)");

                    b.Property<string>("ds_CNPJ_Parametro")
                        .IsRequired()
                        .HasColumnType("character(20)");

                    b.Property<string>("ds_Email_Parametro")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<string>("ds_Endereco_Parametro")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<string>("ds_Nome_Parametro")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<string>("ds_Presidente_Parametro")
                        .IsRequired()
                        .HasColumnType("character(100)");

                    b.Property<string>("ds_Site_Parametro")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<string>("ds_Tesoureiro_Parametro")
                        .IsRequired()
                        .HasColumnType("character(100)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.Property<int>("telefone_id")
                        .HasColumnType("integer");

                    b.Property<int>("uf_id")
                        .HasColumnType("integer");

                    b.HasKey("parametro_id");

                    b.ToTable("Parametro");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Perfis", b =>
                {
                    b.Property<int>("perfil_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Nome_Perfil")
                        .IsRequired()
                        .HasColumnType("character(100)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.HasKey("perfil_id");

                    b.ToTable("Perfil");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Pessoas", b =>
                {
                    b.Property<int>("pessoa_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_CEP_Pessoa")
                        .IsRequired()
                        .HasColumnType("character(10)");

                    b.Property<string>("ds_Email_Pessoa")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<string>("ds_Endereco_Pessoa")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<string>("ds_Nome_Pessoa")
                        .IsRequired()
                        .HasColumnType("character(200)");

                    b.Property<string>("ds_Senha_Pessoa")
                        .IsRequired()
                        .HasColumnType("character(10)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Cadastro_Pessoa")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.Property<int>("perfil_id")
                        .HasColumnType("integer");

                    b.Property<int>("telefone_id")
                        .HasColumnType("integer");

                    b.Property<int>("uf_id")
                        .HasColumnType("integer");

                    b.HasKey("pessoa_id");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Reservas", b =>
                {
                    b.Property<int>("reserva_id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("dt_Data_Reserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("obra_id")
                        .HasColumnType("integer");

                    b.Property<int>("pessoa_id")
                        .HasColumnType("integer");

                    b.HasKey("reserva_id");

                    b.ToTable("Reserva");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Telefones", b =>
                {
                    b.Property<int>("telefone_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_DDD_Telefone")
                        .IsRequired()
                        .HasColumnType("character(10)");

                    b.Property<string>("ds_Numero_Telefone")
                        .IsRequired()
                        .HasColumnType("character(10)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.Property<int>("tipo_telefone_id")
                        .HasColumnType("integer");

                    b.HasKey("telefone_id");

                    b.ToTable("Telefone");
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.TipoAcervos", b =>
                {
                    b.Property<int>("tipo_acervo_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Nome_Tipo_Acervo")
                        .IsRequired()
                        .HasColumnType("character(100)");

                    b.Property<string>("ds_Prazo_Dia_Acervo")
                        .IsRequired()
                        .HasColumnType("character(2)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.HasKey("tipo_acervo_id");

                    b.ToTable("TipoAcervo");

                    b.HasData(
                        new
                        {
                            tipo_acervo_id = 1,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Acervo = "CD VÍDEO",
                            ds_Prazo_Dia_Acervo = "15",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_acervo_id = 2,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Acervo = "DVD",
                            ds_Prazo_Dia_Acervo = "15",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_acervo_id = 3,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Acervo = "FITA K7",
                            ds_Prazo_Dia_Acervo = "15",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_acervo_id = 4,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Acervo = "LIVRO",
                            ds_Prazo_Dia_Acervo = "30",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_acervo_id = 5,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Acervo = "OUTRO",
                            ds_Prazo_Dia_Acervo = "30",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_acervo_id = 6,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Acervo = "PERIÓDICO",
                            ds_Prazo_Dia_Acervo = "30",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        });
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.TipoAutores", b =>
                {
                    b.Property<int>("tipo_autor_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Nome_Tipo_Autor")
                        .IsRequired()
                        .HasColumnType("character(100)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.HasKey("tipo_autor_id");

                    b.ToTable("TipoAutor");

                    b.HasData(
                        new
                        {
                            tipo_autor_id = 1,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Autor = "ESPIRITUAL",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_autor_id = 2,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Autor = "INTUÍDO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_autor_id = 3,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Autor = "OUTRO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_autor_id = 4,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Autor = "PSICOGRÁFICO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        });
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.TipoObras", b =>
                {
                    b.Property<int>("tipo_obra_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Nome_Tipo_Obra")
                        .IsRequired()
                        .HasColumnType("character(100)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.HasKey("tipo_obra_id");

                    b.ToTable("TipoObra");

                    b.HasData(
                        new
                        {
                            tipo_obra_id = 1,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "AUTOAJUDA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 2,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "BIBLIOGRAFIA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 3,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "BIOGRAFIA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 4,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "CARTAS",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 5,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "CITAÇÕES",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 6,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "CRÔNICA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 7,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "CONFERÊNCIA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 8,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "DOCUMENTÁRIO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 9,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "ESTUDO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 10,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "ENTREVISTA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 11,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "FILME",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 12,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "HISTÓRIA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 13,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "MEDITAÇÃO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 14,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "MENSAGEM",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 15,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "PERGUNTAS",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 16,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "OUTRA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 17,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "POESIA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 18,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "PRECE",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 19,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "PALESTRA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 20,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "REFLEXÃO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 21,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "RÁDIO NOVELA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 22,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "SEMINÁRIO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_obra_id = 23,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_Tipo_Obra = "SEMINÁRIO MUSICAL",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        });
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.TipoTelefones", b =>
                {
                    b.Property<int>("tipo_telefone_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Tipo_Telefone")
                        .IsRequired()
                        .HasColumnType("character(30)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.HasKey("tipo_telefone_id");

                    b.ToTable("TipoTelefone");

                    b.HasData(
                        new
                        {
                            tipo_telefone_id = 1,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Tipo_Telefone = "CELULAR",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_telefone_id = 2,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Tipo_Telefone = "COMERCIAL",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            tipo_telefone_id = 3,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Tipo_Telefone = "RESIDENCIAL",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        });
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Unidade_Federativas", b =>
                {
                    b.Property<int>("uf_id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("alterou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<int>("criou_Registro_id")
                        .HasColumnType("integer");

                    b.Property<string>("ds_Nome_UF")
                        .IsRequired()
                        .HasColumnType("character(100)");

                    b.Property<string>("ds_Sigla_UF")
                        .IsRequired()
                        .HasColumnType("character(2)");

                    b.Property<DateTime>("dt_Data_Alteracao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("dt_Data_Criacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("in_Situacao_Registro")
                        .HasColumnType("boolean");

                    b.HasKey("uf_id");

                    b.ToTable("Unidade_Federativas");

                    b.HasData(
                        new
                        {
                            uf_id = 1,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "ACRE",
                            ds_Sigla_UF = "AC",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 2,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "ALAGOAS",
                            ds_Sigla_UF = "AL",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 3,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "AMAZONAS",
                            ds_Sigla_UF = "AM",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 4,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "AMAPÁ",
                            ds_Sigla_UF = "AP",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 5,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "BAHIA",
                            ds_Sigla_UF = "BA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 6,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "CEARÁ",
                            ds_Sigla_UF = "CE",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 7,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "DISTRITO FEDERAL",
                            ds_Sigla_UF = "DF",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 8,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "ESPÍRITO SANTO",
                            ds_Sigla_UF = "ES",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 9,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "GOIÁS",
                            ds_Sigla_UF = "GO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 10,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "MARANHÃO",
                            ds_Sigla_UF = "MA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 11,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "MINAS GERAIS",
                            ds_Sigla_UF = "MG",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 12,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "MATO GROSSO DO SUL",
                            ds_Sigla_UF = "MS",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 13,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "MATO GROSSO",
                            ds_Sigla_UF = "MT",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 14,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "PARÁ",
                            ds_Sigla_UF = "PA",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 15,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "PARAÍBA",
                            ds_Sigla_UF = "PB",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 16,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "PERNAMBUCO",
                            ds_Sigla_UF = "PE",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 17,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "PIAUÍ",
                            ds_Sigla_UF = "PI",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 18,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "PARANÁ",
                            ds_Sigla_UF = "PR",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 19,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "RIO DE JANEIRO",
                            ds_Sigla_UF = "RJ",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 20,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "RIO GRANDE DO NORTE",
                            ds_Sigla_UF = "RN",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 21,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "RONDÔNIA",
                            ds_Sigla_UF = "EO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 22,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "RORAIMA",
                            ds_Sigla_UF = "RR",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 23,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "RIO GRANDE DO SUL",
                            ds_Sigla_UF = "RS",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 24,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "SANTA CATARINA",
                            ds_Sigla_UF = "SC",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 25,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "SERGIPE",
                            ds_Sigla_UF = "SE",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 26,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "SÃO PAULO",
                            ds_Sigla_UF = "SP",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        },
                        new
                        {
                            uf_id = 27,
                            alterou_Registro_id = 0,
                            criou_Registro_id = 1,
                            ds_Nome_UF = "TOCANTINS",
                            ds_Sigla_UF = "TO",
                            dt_Data_Alteracao = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            dt_Data_Criacao = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Local),
                            in_Situacao_Registro = true
                        });
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Funcoes", b =>
                {
                    b.HasOne("sb_ceak.Dominio.Entidade.Perfis", "Perfil")
                        .WithMany("Funcao")
                        .HasForeignKey("perfil_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("sb_ceak.Dominio.Entidade.Operacoes", b =>
                {
                    b.HasOne("sb_ceak.Dominio.Entidade.Funcoes", "Funcao")
                        .WithMany("Operacao")
                        .HasForeignKey("funcao_id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
